#!/bin/bash

# Perform system upgrades
sudo apt update && sudo apt install build-essential git curl jq tree htop wget ncdu pkg-config libssl-dev git-lfs clang tmux -y

# Download necessary files
wget https://github.com/penumbra-zone/penumbra/releases/download/v0.66.0/pd-x86_64-unknown-linux-gnu.tar.xz
wget https://github.com/penumbra-zone/penumbra/releases/download/v0.66.0/pcli-x86_64-unknown-linux-gnu.tar.xz
wget https://github.com/cometbft/cometbft/releases/download/v0.37.2/cometbft_0.37.2_linux_amd64.tar.gz

# Extract downloaded files
sudo tar -xvf cometbft_0.37.2_linux_amd64.tar.gz
sudo tar -xvf pcli-x86_64-unknown-linux-gnu.tar.xz
sudo tar -xvf pd-x86_64-unknown-linux-gnu.tar.xz

# Move binaries to /usr/bin
sudo mv cometbft_0.37.2_linux_amd64/cometbft /usr/bin
sudo mv pcli-x86_64-unknown-linux-gnu/pcli /usr/bin
sudo mv pd-x86_64-unknown-linux-gnu/pd /usr/bin

# Display version information
cometbft version
pcli --version
pd --version

# Clean up unnecessary files
rm CHANGELOG.md cometbft_0.37.2_linux_amd64.tar.gz LICENSE pcli-x86_64-unknown-linux-gnu.tar.xz pd-x86_64-unknown-linux-gnu.tar.xz README.md SECURITY.md UPGRADING.md
rm -rf pcli-x86_64-unknown-linux-gnu pd-x86_64-unknown-linux-gnu

# Create and configure systemd service for pd
printf "[Unit]
Description=pd node
After=network-online.target

[Service]
User=root
ExecStart=`which pd` start --home ~/.penumbra/testnet_data/node0/pd
Restart=on-failure
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target" | sudo tee /etc/systemd/system/pd.service > /dev/null

sudo systemctl daemon-reload
sudo systemctl enable pd
sudo systemctl start pd

# Download the testnet files
pd testnet join --external-address 64.176.188.109:26656 --moniker alterkahn

# Start cometbft in a new tmux session
tmux new -s cometbft
cometbft start --home ~/.penumbra/testnet_data/node0/cometbft

# Detach tmux session

# Initialize soft-kms and import phrase
pcli init soft-kms import-phrase

# Input phrase and press Enter

# Extract and upload validator definition
grep -A3 pub_key ~/.penumbra/testnet_data/node0/cometbft/config/priv_validator_key.json

pcli validator definition template \
    --tendermint-validator-keyfile ~/.penumbra/testnet_data/node0/cometbft/config/priv_validator_key.json \
    --file validator.toml

# Configure your validator data
nano validator.toml

# Check sync status
curl -s http://localhost:26657/status | jq .result.sync_info.catching_up

# When the chain is synced, run your validator by uploading validator definition file
pcli validator definition upload --file validator.toml

# List validators and find your moniker there
pcli q validator list -t

# Find your validator’s identity key
pcli validator identity

# Check the balance
pcli view balance

# Delegate to ypur validator
pcli tx delegate 100penumbra --to [YOUR_VALIDATOR_IDENTITY_KEY]
